### PR TITLE
bash Script for generating docs

### PR DESCRIPTION
**Pull request by nukulb**
bash script for generating the docs. It copies the template and the plugin and then calls the jsrun.jar.

### CODE REVIEW

**Comment by tneil** [comment]
Is this the same as the genDoc.bat for Windows but now also for Mac?  If they are intended to be the same, can we attempt to make the input parameters (if any) the same between the bat and the bash script?

**Comment by tneil** [comment]
Could we also add the following:
- README.md file for the /build directory that talks about how to use both the genDoc.bat and genDoc bash files
- updated the main root repo README.md that outlines that there are also mac/windows build scripts that can be found in the /build directory of the repo

**Comment by tneil** [comment]
I have an associated feature Issue of #194

**Comment by nukulb** [comment]
Its modeled after the genDoc.bat file so the input parameters are the same.

There is a usage included in bash scripts which talks about how to use it.

I will add both the README.md and make the note on the main page.

Do you want me to add this as a part of the same pull request?

**Comment by tneil** [comment]
Sure.. just make it part of the same pull request

**Comment by nukulb** [comment]
Took some editing in github to get it to format correctly but I think what I have now works.

**Comment by nukulb** [comment]
I need to find a way to have them as relative paths.
I will update.

**Comment by cdelcol** [comment]
Manually merged pull request.

**Pull request closed without merging**
