### PR TITLE
Added BB7.0 to the drop down filter and included APIs supported on BB6.0

### PR DESCRIPTION
**Pull request by jachoi**

### CODE REVIEW

**Comment by jeffheifetz** [comment]
Do you think we could update the code to generate all of the headers and the filters so that we only ever have to change this in one place in the future?

**Comment by jachoi** [comment]
Are there other headers and/or filters that I will be needing to put in? I was only told to put in BB7.0 filter in the drop down menu.

**Comment by cpinzon** [comment]
Jeff, what would you suggest in terms of an update of code to avoid changing this all over the place once we need a new header and filter?

**Comment by jeffheifetz** [comment]
Well we've already mostly centralized the logic to that BBTag class so I would think make some more methods there. At the very least only the BBTag class will need to change.

**Comment by jeffheifetz** [comment]
Also you're missing the changes needed in the featureList.tmpl. They should be identical to those in the Toc

**Comment by cpinzon** [comment]
Yup, sorry about that James, didn't catch that. Jeff, makes sense. I can bring this to Peter's attention.

**Comment by jachoi** [comment]
Sure if you can that would be nice. Thanks.

**Comment by cpinzon** [comment]
James, can you add the code in the featureList.tmpl file and push it so it can be added to the code review?

**Comment by jachoi** [comment]
Done adding the code in featureList.tmpl file.

**Comment by cpinzon** [comment]
This looks good. I generated the docs and no apparent problems.

**Comment by cdelcol** [comment]
closed via commit #0a86198

**Pull request closed without merging**
