### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by tneil**
updated jsdocs formatting structure, OS tagging, examples and links to HTML5 toolkit

### CODE REVIEW

**Comment by jeffheifetz** [comment]
There is no need for support tags at the namespace level. To prevent errors the templates calculate the support based on an object's children.

**Comment by tneil** [comment]
Cool.. One less thing to update :)

**Comment by tneil** [comment]
We have been using @default for other constants, so I just followed that pattern :)

Do we want to use @returns instead?  I know that the @default is displaying properly in the HTML, I haven't tried @returns

**Comment by ghost** [comment]
Tim, is this pull request ready for a merge?

**Comment by tneil** [comment]
sure.. it is ready for merge.. I'm working on the Phone/Call logs now... but I will send it as a follow up pull request

**Comment by ghost** [comment]
OK. I'm merging it right now to the master.

**Pull request merged**
