### PR TITLE
Added two new error codes and a new callback pushserviceconnectionready for when the underlying Push Service goes down and the connection needs to be re-established.

### PR DESCRIPTION
**Pull request by mdandrea**
The two new error codes are: PUSH_SERVICE_CONNECTION_CLOSED and PUSH_SERVICE_CONNECTION_PERMISSION_ERROR.
As well as two additional constants: CREATE_OPERATION and LAUNCH_APP_ON_PUSH_OPERATION.

The new callback is pushServiceConnectionReadyCallback.

*\* Existing WebWorks applications will not be impacted by these changes. **

### CODE REVIEW

**Comment by mdandrea** [comment]
The API changes can be found here: https://github.com/blackberry/cordova-blackberry-plugins/pull/19

**Comment by mdandrea** [comment]
Note that these API doc changes will only be applicable to Cordova.

**Comment by bryanhiggins** [comment]
I have created a new "cordova" branch to capture these changes. Could you please close this and re-open against that branch?

**Comment by mdandrea** [comment]
@bryanhiggins Could you please give me read+write access to this repo and I'll make the change to be based off of the "cordova" branch.  Thanks!

**Comment by mdandrea** [comment]
Or, I could make changes to a fork of the repo if that would be preferable I guess.

**Comment by bryanhiggins** [comment]
@mdandrea i don't actually have admin access. Just rebase your local branch off of blackberry/cordova and push to blackberry-webworks. Then create a pull request from blackberry-webworks to blackberry.

**Comment by mdandrea** [comment]
Closing.  Have opened new pull request: https://github.com/blackberry/WebWorks-API-Docs/pull/465

**Pull request closed without merging**
