### PR TITLE
Updating localstorage to mention 25MB limit on BB10

### PR DESCRIPTION
**Pull request by jeffheifetz**

### CODE REVIEW

**Comment by kwallis** [comment]
r+

**Comment by jeffheifetz** [comment]
This is 25mb per domain, correct?

**Comment by kwallis** [comment]
Good question, you may need to confirm.

---

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by jeffheifetz** [comment]
Confirmed with otto cheung, updating commit

**Comment by jeffheifetz** [comment]
Merged Manually

**Pull request closed without merging**
