### PR TITLE
Updated the default return text for URI functions

### PR DESCRIPTION
**Pull request by jeffheifetz**
It now generates a default message and table describing the return data.

Here is an example

### CODE REVIEW

**Comment by rwmtse** [comment]
Actually data is not null even if code=1, data always contains the params that were passed in, even if the call didn't finish successfully.

**Comment by rwmtse** [comment]
And as discussed, if we are having that one document that covers all URI-based APIs in general, the table should be in that document instead of in every single URI-based API

**Comment by jeffheifetz** [comment]
So maybe just a blurb saying that for full documentation checkout the page and a link?

**Comment by rwmtse** [comment]
Yea, I think so.

**Pull request closed without merging**
