### PR TITLE
2.1.1

### PR DESCRIPTION
**Pull request by marek**
api doc updates for 2.1.1

### CODE REVIEW

**Comment by tneil** [comment]
Are there any updates for marking BB7 support in the templates and supported on charts?  Or would this be a different pull request?

**Comment by marek** [comment]
Not part of this pull.. I think someone else was adding BB70+ support.

**Comment by tneil** [comment]
ok

-----Original Message-----

**Comment by marek** [comment]
BB70+ is in: blackberry/WebWorks-API-Docs@0a86198ad5bd7f9164449e6e73d589760a654966

**Comment by cdelcol** [comment]
I cherry picked the changes and created 3 clean commits. Marek, can you have a quick look to make sure I got everything? This pull request can then just be closed after the review.

**Comment by marek** [comment]
Looks good except for a typo I did in payment.

**Pull request closed without merging**
