### PR TITLE
Updated all of the Phone jsdocs

### PR DESCRIPTION
**Pull request by tneil**
The phone jsdocs should be all good to go!

### CODE REVIEW

**Comment by jeffheifetz** [comment]
The reason why Marek had all those .prototypes is because it differentiates between static and instance methods. Do we not want that designation?

**Comment by tneil** [comment]
no problem... didn't know that was the reason.. i can change them back.  i added a bunch of updated descriptions and toc changes as well that i will keep

**Comment by tneil** [comment]
Ok.. I changed the structure back to the way it was before to denote static and member functions/properties.  Have the templates been updated so that you don't get the hash #?  right now anything that uses 'prototype' has a # instead of a '.' before the function/property name.  

I would assume that it is supposed to be a '.' and we place the word 'static' in front of the function to denote that it is a static function or property

**Comment by jeffheifetz** [comment]
I will make a change in the templates to denote static with the keyword vs the hash

**Pull request merged**
