### PR TITLE
Update permit for HTML5 geolocation

### PR DESCRIPTION
**Pull request by bryanhiggins**
Issue #406

### CODE REVIEW

**Comment by nukulb** [comment]
Not true for playbook

**Comment by bryanhiggins** [comment]
Good point! I amended the commit. Let me know if it is ok - I didn't see other examples of multiple permit attributes.

**Comment by jeffheifetz** [comment]
Thats because we have never had this come up before. Currently there is a way to specify that a featureId is valid for only a given set of OSes (using the  type {} option). 

Would we like to add this ability for permissions?

**Comment by bryanhiggins** [comment]
I suggest we merge this into master ASAP.

It seems to be causing confusion in the community.

https://github.com/blackberry/BB10-WebWorks-Framework/issues/487

**Comment by jeffheifetz** [comment]
Issue tracked in #419, r+

**Comment by jeffheifetz** [comment]
Woops, needs to be retargetted to master

**Pull request closed without merging**
