### PR TITLE
Delta master merge

### PR DESCRIPTION
**Pull request by jeffheifetz**

### CODE REVIEW

**Comment by ababut** [comment]
this is applying the same commit 3 times...why not apply one of them?

**Comment by jeffheifetz** [comment]
How?

**Comment by ababut** [comment]
interactive rebase: git rebase -i HEAD~4 on your branch and only pick one of the commits. Git will get rid of the other ones. 

Ideally this would've been done before you pushed your branch to Github, but if you're confident that no one forked your repo, you can force push the branch and update the pull request.

**Comment by cdelcol** [comment]
closed with commit 2a2227c6df2a3ec9ab9af687ac8fdc81018362d4

**Pull request closed without merging**
